### ISSUE TITLE
Improve Label Issue Identification Metrics in Datalab Quickstart tutorial

### ISSUE THREAD

**Issue by elisno** [cleanlab/cleanlab#1149]
# Details

The current method, introduced in #1118,  for testing identified label issues in [datalab_quickstart.ipynb](https://raw.githubusercontent.com/cleanlab/cleanlab/master/docs/source/tutorials/datalab/datalab_quickstart.ipynb)
has a low Jaccard Similarity score (~0.4) . We need to switch to more relevant metrics like precision@k and recall@k for evaluating `identified_label_issues_indices` and `label_issue_indices`.

**Tasks:**

- [ ] 1. **Implement precision@k and recall@k:**
   - Implement `precision_at_k`:
    ```python
    def precision_at_k(predicted_indices, true_indices, k):
        return len(set(predicted_indices[:k]).intersection(set(true_indices))) / k
    ```
   - Implement `recall_at_k`:
    ```python
    def recall_at_k(predicted_indices, true_indices, k):
        return len(set(predicted_indices[:k]).intersection(set(true_indices))) / len(true_indices)
    ```
- [ ] 2. **Update Test Cases:**
   - Replace the Jaccard Similarity test with precision@k and recall@k:
    ```python
    k = len(label_issue_indices)
    assert precision_at_k(predicted_label_issues_indices, label_issue_indices, k) > test_threshold_1
    assert recall_at_k(predicted_label_issues_indices, label_issue_indices, k) > test_threshold_2
    ```
- [ ] 3. **Add Test Case for `.query("is_label_issue")`:**
   - Compare metrics with and without using `.query("is_label_issue")`.

**Expected Outcome:**
- Improved evaluation of identified label issues using precision@k and recall@k.
- Test case showing impact of `.query("is_label_issue")`.

---

Please follow up on these tasks and submit a new pull request with your findings and improvements.

**Comment by jwmueller** [comment]
completed in  https://github.com/cleanlab/cleanlab/pull/1166/
